---
- hosts: localhost
  tasks:
    - name: Install packages
      include_tasks: "{{ ansible_facts['distribution'] }}.yml"

    - name: Create ~/github
      file:
        state: directory
        path: ~/github

    - name: Clone direnv/direnv
      git:
        repo: https://github.com/direnv/direnv.git
        dest: ~/github/direnv

    - name: Clone alacritty/alacritty
      git:
        repo: https://github.com/alacritty/alacritty.git
        dest: ~/github/alacritty

    - name: Clone tmux/tmux
      git:
        repo: https://github.com/tmux/tmux.git
        dest: ~/github/tmux
